### ISSUE TITLE
Is this code suitable for data in nii format? Yes? How to use? Thanks.

### ISSUE THREAD

**Issue by fzhan007** [MontaEllis/Pytorch-Medical-Segmentation#10]
If Yes? How to use? Thanks.

**Comment by MontaEllis** [comment]
Absolutely. Please check https://github.com/MontaEllis/Pytorch-Medical-Segmentation#prepare-your-dataset

**Comment by fzhan007** [comment]
Thank you for your attention. You mean to convert NII to.mhd.zraw and then use this program.

**Comment by MontaEllis** [comment]
No, I mean just change the settings in hparam.py.
