### ISSUE TITLE
train

### ISSUE THREAD

**Issue by He9702** [MontaEllis/Pytorch-Medical-Segmentation#11]
Can this project not be trained except for data files in *.mhd format? 
![image](https://user-images.githubusercontent.com/71333170/112752709-e28c9680-9006-11eb-9c2c-1f351c1b704e.png)
![image](https://user-images.githubusercontent.com/71333170/112752723-f59f6680-9006-11eb-87b2-e5b7bfb99de1.png)

**Comment by MontaEllis** [comment]
Of course. Please check your data directory.
