### ISSUE TITLE
训练相关

### ISSUE THREAD

**Issue by LoinJi** [MontaEllis/Pytorch-Medical-Segmentation#12]
您好！有一个关于训练结果的问题想要请教一下。
我使用的网上下载的胰腺数据集，原数据和标签都是 nii.gz 格式的，因为是3d数据，所以用的是3d的网络来跑的。是在本地的计算机上跑的代码。默认设置的epoch是100
参数设置如下：
![image](https://user-images.githubusercontent.com/51920285/112779035-6fbc0380-9078-11eb-9a36-ca801e2f6b73.png)
但是我训练到后面，loss值是在下降，但是dice值就一直是0了，false_positive_rate以及false_negative_rate也很不正常，如下所示：
![image](https://user-images.githubusercontent.com/51920285/112779203-bf9aca80-9078-11eb-8a0b-7bc7e35c8837.png)
想请问原因可以能为什么呢？是否和epoch数有关？因为我看您的原代码是500000，我设置100已经需要跑一段时间了。
其他的参数是否有要根据数据的三维尺寸调整的呢？
感谢回复！

**Comment by LoinJi** [comment]
会不会和数据量小有关呢？因为还在初期阶段，所以只用了10个病例来试试。

**Comment by MontaEllis** [comment]
请把你的训练log给我看一下

**Comment by LoinJi** [comment]
![image](https://user-images.githubusercontent.com/51920285/112793131-4f4f7180-9097-11eb-8bcc-020b4b9dc21b.png)
是这些文件吗？

**Comment by MontaEllis** [comment]
tensorboard的

**Comment by LoinJi** [comment]
我是在本地跑的，所以没有做tensorboard可视化

**Comment by LoinJi** [comment]
我刚才可视化了一下，结果是这样的。
![image](https://user-images.githubusercontent.com/51920285/112799543-13b9a500-90a1-11eb-95a6-d1c5ffa97e70.png)
我现在还在跑

**Comment by LoinJi** [comment]
这是我现在用的数据和标签
![image](https://user-images.githubusercontent.com/51920285/112800268-04872700-90a2-11eb-9bda-61b2a241c559.png)

**Comment by MontaEllis** [comment]
你的label是0-1吗？用的是最新的代码吗？

**Comment by LoinJi** [comment]
是最新的代码，标签是这样的
![image](https://user-images.githubusercontent.com/51920285/112813595-f391e200-90b0-11eb-90c0-45f44d06e750.png)
应该是0-1的吧

**Comment by MontaEllis** [comment]
mitk可以看那个值的，点着看一下。你可以加我微信聊下

**Comment by LoinJi** [comment]
好的，谢谢

**Comment by daisysong1** [comment]
> mitk可以看那个值的，点着看一下。你可以加我微信聊下

我也有问题想请教，如何加您的微信呀
