### ISSUE TITLE
训练时候tensorboard可视化效果挺好，测试出来可视化不咋好

### ISSUE THREAD

**Issue by NBIronman** [MontaEllis/Pytorch-Medical-Segmentation#13]
你好，我分割训练LITS肝脏，tensorboard可视化，loss，dice我觉得都还不错。
![image](https://user-images.githubusercontent.com/80090145/116421727-b0728c80-a871-11eb-9537-1dd70db02655.png)
![image](https://user-images.githubusercontent.com/80090145/116421854-cc762e00-a871-11eb-9ab0-534bb7b0e949.png)
左边是预测的，右边是分割的，但是我测试的结果可视化之后，一点都没分割出来，我找了好久也没发现原因，想问问您，是拼接的问题吗？？
![image](https://user-images.githubusercontent.com/80090145/116422167-0ba47f00-a872-11eb-9980-810f81bd5df4.png)

**Comment by MontaEllis** [comment]
不应该吧，检查下自己的数据

**Comment by NBIronman** [comment]
> 不应该吧，检查下自己的数据

我把测试的数据和标签可视化都是正常的，不知道怎么回事

**Comment by MontaEllis** [comment]
微信联系我一下？

**Comment by NBIronman** [comment]
> 微信联系我一下？

嗯嗯，好的

**Comment by NBIronman** [comment]
哈哈，是我自己数据忘记预处理了，才导致这样的，谢谢作者啦

**Comment by alenchen-0606** [comment]
@NBIronman 請問您是忘記甚麼預處理，可以分享一下嗎? 謝謝~
