### ISSUE TITLE
很好的项目，对TensorBoard有个疑问

### ISSUE THREAD

**Issue by testnobody** [MontaEllis/Pytorch-Medical-Segmentation#15]
我看了下可能因为数据量比较大 一个epoch 就收敛的差不多了 但是我查看TensorBoard显示dice  false_negtive_rate false_positive_rate 都没结果 是我的姿势不对嘛。
![image](https://user-images.githubusercontent.com/70645370/117922532-35a37a00-b325-11eb-94b5-9e0f06f41942.png)

**Comment by MontaEllis** [comment]
应该不会的，是不是数据的label有问题？可以把source和label给我看看

**Comment by testnobody** [comment]
感谢大佬，已解决，## 大佬的意见：和我一样是2D图像的把hparam的patch_size 调大可以让LOSS降低稳定，然后把main.py的251行的 y = y/255.注释掉 可以解决不假阴性率和假阳性率计算的问题

**Comment by wmh02240** [comment]
> 感谢大佬，已解决，
> 
> ## 大佬的意见：
> 和我一样是2D图像的把hparam的patch_size 调大可以让LOSS降低稳定，然后把main.py的251行的 y = y/255.注释掉 可以解决假阴性率和假阳性率计算的问题

你好，请问下怎么准备自己的自定义2d数据集进行训练？

**Comment by MontaEllis** [comment]
按readme里写的格式就行

**Comment by wmh02240** [comment]
> 按readme里写的格式就行
![image](https://user-images.githubusercontent.com/42089945/121453884-76e68280-c9d4-11eb-9e1c-392ddade6ad2.png)
作者你好，in_class=1指的是输入图像的通道数吗？

**Comment by wmh02240** [comment]
> 按readme里写的格式就行

谢谢指导。
