### ISSUE TITLE
图片可以直接使用png或者jpeg吗？

### ISSUE THREAD

**Issue by 775397252** [MontaEllis/Pytorch-Medical-Segmentation#16]
请问一下，图片可以直接使用png或者jpeg的图片或者标注吗？

**Comment by MontaEllis** [comment]
png可以的，其他的没试过

**Comment by 775397252** [comment]
配置了`train_or_test = 'test'`，`fold_arch = '*.png'` ,发现test预测输出的不是png格式，生成log也不是？

**Comment by MontaEllis** [comment]
嗯，train和test的输出代码也要修改下
