### ISSUE TITLE
hi, question about the image size of .nrrd format.

### ISSUE THREAD

**Issue by Jihunlee326** [MontaEllis/Pytorch-Medical-Segmentation#17]
Thanks for your github.

I'm testing with .nrrd format.
however, there is an issue where the resulting image is enlarged.
(ex: input size:256x256x256 --> result : 128x128x128)
Also, the image is enlarged to 32-bit or greater precision.
What part of main.py should I edit?

**Comment by MontaEllis** [comment]
The size of the result will strictly correspond to the input, so please check your input and output carefully.

**Comment by Jihunlee326** [comment]
My input shape is 256x256x256.
and I set hparam.py like this:

    crop_or_pad_size = 256,256,256
    patch_size = 128,128,128

    fold_arch = '*.nrrd'

    save_arch = '.nii.gz'

    source_train_dir = '../datasets/source_dataset'
    label_train_dir = '../datasets/label_dataset'
    source_test_dir = '../datasets/source_dataset_test'
    label_test_dir = '../datasets/label_dataset_test'

Is there something I'm missing out on? Please advise.

**Comment by MontaEllis** [comment]
The setting is correct, the results of the network would be 128*128*128 and the results after splicing would be 256*256*256.
