### ISSUE TITLE
hello，how to multi-gpu training？

### ISSUE THREAD

**Issue by zhang5957** [MontaEllis/Pytorch-Medical-Segmentation#19]

**Comment by MontaEllis** [comment]
We would add DDP in the future.

**Comment by zhang5957** [comment]
> We would add DDP in the future. You can modify:
> 
> https://github.com/MontaEllis/Pytorch-Medical-Segmentation/blob/22c1ac83646024428c7198ebf614436a5e97b058/main.py#L2
> 
> to simple multi gpu mode.

when i was training，my dice is always 0.it‘s my data problem?

**Comment by MontaEllis** [comment]
Yes

**Comment by zhang5957** [comment]
> Yes

thanks
