### ISSUE TITLE
prepare data

### ISSUE THREAD

**Issue by b-rookie** [MontaEllis/Pytorch-Medical-Segmentation#20]
你好  请问在哪里添加预处理的代码  我没找到您预处理的代码。

**Comment by MontaEllis** [comment]
可以仔细看下代码

**Comment by b-rookie** [comment]
> 可以仔细看下代码

![image](https://user-images.githubusercontent.com/68233628/133218143-13b78f0c-1306-4f36-9d8d-0d0e2e45a59c.png)
是transform这里吗
