### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by qq1440837150** [MontaEllis/Pytorch-Medical-Segmentation#25]
RuntimeError: More than one value for "spacing" found in subject images:
{'label': (1.0468800067901611, 1.0468800067901611, 2.5),
 'source': (0.712891, 0.712891, 2.49998)}
![image](https://user-images.githubusercontent.com/31851742/134767356-887ebc7b-2911-499a-a8f6-776988f1fbb9.png)

**Comment by MontaEllis** [comment]
您source和label的空间位置没对齐。

**Comment by qq1440837150** [comment]
> 您source和label的空间位置没对齐。

你好，我如果在cmd里面运行这个文件就会报这个错。。。，但是在pycharm里面的python console运行就没报错。。。

**Comment by MontaEllis** [comment]
没对齐肯定是不行的。

**Comment by TroubleMaker369** [comment]
![image](https://github.com/MontaEllis/Pytorch-Medical-Segmentation/assets/78291855/ecb43940-e4c4-4b93-88b2-f66996a4bd6b)

**Comment by TroubleMaker369** [comment]
这个怎么解决
