### ISSUE TITLE
模型训练效果较差

### ISSUE THREAD

**Issue by JohnMasoner** [MontaEllis/Pytorch-Medical-Segmentation#31]
我使用这个版本的 [ResUNet](https://github.com/rishikksh20/ResUnet) 在我的数据上进行训练可以得到0.78左右的 Dice 值. 我使用您的模型对同样的数据进行训练模型无法进行收敛 Dice 值始终处在0.1以下. 我在对模型进行检查后仍未能发现问题.

这是我训练的 log. 其中红色线为2DResUNet, 蓝色线为3D模型.
![image](https://user-images.githubusercontent.com/42313377/147218391-9426222a-bfa9-4036-bbfc-569add48c503.png)

我原始的数据类型为 .dcm 类型, 使用脚本转为 .nii.gz 格式. 我使用 dicompyler 对转后的 .nii.gz 进行检查未发现数据存在问题.

希望能够得到您的回复!

**Comment by MontaEllis** [comment]
标注是0,1?

**Comment by JohnMasoner** [comment]
您好, 我确认了我的标注是0,255. 我使用脚本文件将其转为 0,1 后训练得到的模型效果仍然很差.我在 2D 和 3D 模型均训练 5h 左右, dice 值仍然处在0.1以下.

非常感谢您的回复

**Comment by MontaEllis** [comment]
如果标注没问题的话请关注下source和label是否一一对应

**Comment by JohnMasoner** [comment]
非常感谢您的回复. 我找到了问题所在, 因为我使用numpy将 .dcm 文件 转为 .nii.gz格式, 在读取标注文件时失去的层厚信息,这导致最后生成的 .nii.gz 文件插值效果很差. 以下是我的 .nii.gz 的图像. 
![image](https://user-images.githubusercontent.com/42313377/147463827-eed77007-798d-4b15-a043-69baf19d45c0.png)

您可以随时关闭这个问题. 非常感谢您的回复.

**Comment by MontaEllis** [comment]
👍
