### ISSUE TITLE
我的损失函数从正值一直减小到负数了？并且损失函数的绝对值还在不断增大

### ISSUE THREAD

**Issue by Fuzhiyuan** [MontaEllis/Pytorch-Medical-Segmentation#32]
这该怎么办？

**Comment by Fuzhiyuan** [comment]
学习率也没有更改，一直是0.002

**Comment by JohnMasoner** [comment]
数据格式是dicom格式的吗? 你可以将'main.py'文件中'#print(y.max())'注释掉观察一下 label 的最大值.确保 label 为1.

**Comment by Fuzhiyuan** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by Fuzhiyuan** [comment]
> 数据格式是dicom格式的吗? 你可以将'main.py'文件中'#print(y.max())'注释掉观察一下 label 的最大值.确保 label 为1.

数据格式为.nii.gz
我的模型是3d unet模型

**Comment by Fuzhiyuan** [comment]
> 数据格式是dicom格式的吗? 你可以将'main.py'文件中'#print(y.max())'注释掉观察一下 label 的最大值.确保 label 为1.

还有就是label最大值为1是什么意思啊？不是很明白。

**Comment by JohnMasoner** [comment]
label 的标注格式可以是[0,255], 也可以是 [0,1]. 这个模型作者写的模型仅仅适用0,1格式的标注. 如果无法理解, 可以将'main.py'的'#y[y!=0] = 1'注释取消掉来保证你的label格式为0,1.

**Comment by Fuzhiyuan** [comment]
> label 的标注格式可以是[0,255], 也可以是 [0,1]. 这个模型作者写的模型仅仅适用0,1格式的标注. 如果无法理解, 可以将'main.py'的'#y[y!=0] = 1'注释取消掉来保证你的label格式为0,1.

你好，我想问一下如果我做了这个转换，对我的后续训练会有什么影响吗？如果可以的话，可以留一下国内社交软件联系方式吗？邮箱也可以。

**Comment by JohnMasoner** [comment]
对后续没有影响的, 这一步只是将 label 的标签转为0,1格式,以符合模型对数据的需求. 你可以添加我的微信: MasonMa-
