### ISSUE TITLE
如何让模型可以处理大于1的标签？

### ISSUE THREAD

**Issue by Fuzhiyuan** [MontaEllis/Pytorch-Medical-Segmentation#34]
现在的模型训练后只是把脊椎的所有节都分成一个颜色，我的训练集标签是每相邻节骨头都是不一样的颜色，我也需要这样的推理效果，请问应该怎么处理啊？

**Comment by JohnMasoner** [comment]
Your problem maybe a multi-class task, but your label is binary classification label.

**Comment by MontaEllis** [comment]
我们即将对代码进行一次大的更新，您的需求我们会考虑进去。
