### ISSUE TITLE
关于小数据集下设置aug=true后，会导致测试时outputs值整体小于0.5

### ISSUE THREAD

**Issue by Fuzhiyuan** [MontaEllis/Pytorch-Medical-Segmentation#37]
我自己3d脊椎训练的数据集是7张nii.gz文件，epoch为20，batch为4.
设置aug=true后，进行推理时，手动输出outputs最大值小于0.5，导致result图像为空，但是设置false后就会正常（指result最大值会大于0.5）。
目前还没试验过其他数据集，这一点可以注意一下。

**Comment by Fuzhiyuan** [comment]
还有我在数据集1000张图片下训练100次，损失函数稳定到0.0007附近，但是推理的结果仍不理想，缩小patch_size是一个好的选择吗？准备改成256*256*18

**Comment by MontaEllis** [comment]
这是一个小bug，现在已经修复，谢谢您的建议。

**Comment by Fuzhiyuan** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by Fuzhiyuan** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
