### ISSUE TITLE
the prediction results are all black

### ISSUE THREAD

**Issue by ARnnn** [MontaEllis/Pytorch-Medical-Segmentation#45]
I fixed the errors in the model prediction in the same way as you, but now the prediction results are all black. What's the problem. What I did was a dichotomy. During the test, there was such a warning:
![image](https://user-images.githubusercontent.com/52728076/169189620-9370a2c3-f41e-4738-b615-d51382de5f38.png)

**Comment by ARnnn** [comment]
I solved the above problem, but the predicted result looks very bad
![image](https://user-images.githubusercontent.com/52728076/169193319-46311d25-e4eb-41a5-b119-d78fb3d1acb7.png)
the tensorboard is as follows：
![Uploading image.png…]()

**Comment by MontaEllis** [comment]
I can't see your tensorboard.

**Comment by ARnnn** [comment]
> I can't see your tensorboard.

![image](https://user-images.githubusercontent.com/52728076/169218589-cd2f3f4e-5ef1-45c3-9fdc-4ef5cf4cb2c3.png)

**Comment by MontaEllis** [comment]
Can I see your hparam.py? I guess you set 'croporpad' in a wrong way.

**Comment by ARnnn** [comment]
I set the same parameters of hparam.py as you

**Comment by ARnnn** [comment]
I haven't changed anything except my own dataset

**Comment by MontaEllis** [comment]
You should modify 'croporpad' at your own dataset.

**Comment by ARnnn** [comment]
Different cases in my data have different sizes，so how can I set the croporpad according to my own data?

**Comment by ARnnn** [comment]
In many slices in my case, some contain the parts to be segmented and some do not (the label is all black). Do I need to remove the slices that do not contain the parts to be segmented?

**Comment by MontaEllis** [comment]
> 

Yes.
