### ISSUE TITLE
Thanks for your sharing. I have one question.  Why is the value of BCEWithLogitsLoss negative？

### ISSUE THREAD

**Issue by ssli23** [MontaEllis/Pytorch-Medical-Segmentation#8]

**Comment by MontaEllis** [comment]
1. hp.in_class is the number of the channels of input
2. since your labels are not 0/1

**Comment by ssli23** [comment]
> 1. hp.in_class is the number of the channels of input
> 2. since your labels are not 0/1

how to set labels to 0/1?

**Comment by MontaEllis** [comment]
You can check your data, your label is most likely a png image. Do normalisation on the read process.
