### ISSUE TITLE
医学图像分割数据集

### ISSUE THREAD

**Issue by GZYZG** [MontaEllis/Pytorch-Medical-Segmentation#9]
新入门医学影像分割小白，请问您有医学影像目标分割的数据集吗，在网上找了一段时间，但是都没有找到合适的香瓜的数据集，如果方便的话希望分享以下，谢谢🙏

**Comment by MontaEllis** [comment]
有很多，请自己查下

**Comment by GZYZG** [comment]
> 有很多，请自己查下

好的，谢谢
